/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE "public"."tdoctors_doctor_id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "public"."tdoctors_doctor_id_seq" IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE "public"."thospitals_hospital_id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "public"."thospitals_hospital_id_seq" IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE "public"."thospitals_department_hospital_department_id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "public"."thospitals_department_hospital_department_id_seq" IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE "public"."tmedical_records_medical_record_id_seq" INCREMENT BY 1;
COMMENT ON SEQUENCE "public"."tmedical_records_medical_record_id_seq" IS 'DbWrench Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: "public"."tdoctors" ************************/

/* Build Table Structure */
CREATE TABLE "public"."tdoctors"
(
	doctor_id INTEGER DEFAULT nextval('"public"."tdoctors_doctor_id_seq"'::regclass) NOT NULL,
	doctor_name VARCHAR(50) NOT NULL,
	doctor_surname VARCHAR(50) NOT NULL,
	doctor_patronymic VARCHAR(50) NULL,
	hospital_department_id INTEGER NOT NULL
);

/* Add Primary Key */
ALTER TABLE "public"."tdoctors" ADD CONSTRAINT "pktdoctors"
	PRIMARY KEY (doctor_id);


/******************** Add Table: "public"."thospitals" ************************/

/* Build Table Structure */
CREATE TABLE "public"."thospitals"
(
	hospital_id INTEGER DEFAULT nextval('"public"."thospitals_hospital_id_seq"'::regclass) NOT NULL,
	hospital_name VARCHAR(100) NULL,
	hospital_adress VARCHAR(150) NULL
);

/* Add Primary Key */
ALTER TABLE "public"."thospitals" ADD CONSTRAINT "pkthospitals"
	PRIMARY KEY (hospital_id);


/******************** Add Table: "public"."thospital_departments" ************************/

/* Build Table Structure */
CREATE TABLE "public"."thospital_departments"
(
	hospital_department_id INTEGER DEFAULT nextval('"public"."thospitals_department_hospital_department_id_seq"'::regclass) NOT NULL,
	hospital_id INTEGER NOT NULL,
	hospital_department BIGINT NULL
);

/* Add Primary Key */
ALTER TABLE "public"."thospital_departments" ADD CONSTRAINT "pkthospitals_department"
	PRIMARY KEY (hospital_department_id);


/******************** Add Table: "public"."tmedical_records" ************************/

/* Build Table Structure */
CREATE TABLE "public"."tmedical_records"
(
	medical_record_id INTEGER DEFAULT nextval('"public"."tmedical_records_medical_record_id_seq"'::regclass) NOT NULL,
	doctor_id INTEGER NOT NULL,
	patient_id VARCHAR(128) NOT NULL,
	medical_record TEXT NOT NULL,
	medical_record_date TIMESTAMP NOT NULL
);

/* Add Primary Key */
ALTER TABLE "public"."tmedical_records" ADD CONSTRAINT "pktmedical_records"
	PRIMARY KEY (medical_record_id);


/******************** Add Table: "public"."tpatients" ************************/

/* Build Table Structure */
CREATE TABLE "public"."tpatients"
(
	patient_id VARCHAR(128) NOT NULL,
	patient_name VARCHAR(50) NOT NULL,
	patient_surname VARCHAR(50) NOT NULL,
	patient_patronymic VARCHAR(50) NULL
);

/* Add Primary Key */
ALTER TABLE "public"."tpatients" ADD CONSTRAINT "pktpatients"
	PRIMARY KEY (patient_id);





/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_tdoctors_thospitals_department */
ALTER TABLE "public"."tdoctors" ADD CONSTRAINT "fk_tdoctors_thospitals_department"
	FOREIGN KEY (hospital_department_id) REFERENCES "public"."thospital_departments" (hospital_department_id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_thospitals_department_thospitals */
ALTER TABLE "public"."thospital_departments" ADD CONSTRAINT "fk_thospitals_department_thospitals"
	FOREIGN KEY (hospital_id) REFERENCES "public"."thospitals" (hospital_id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tmedical_records_tdoctors */
ALTER TABLE "public"."tmedical_records" ADD CONSTRAINT "fk_tmedical_records_tdoctors"
	FOREIGN KEY (doctor_id) REFERENCES "public"."tdoctors" (doctor_id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;

/* Add Foreign Key: fk_tmedical_records_tpatients */
ALTER TABLE "public"."tmedical_records" ADD CONSTRAINT "fk_tmedical_records_tpatients"
	FOREIGN KEY (patient_id) REFERENCES "public"."tpatients" (patient_id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;