package com.khomenkocode.graduationproject.entities;
// Generated 07.05.2018 15:13:57 by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Tdoctors generated by hbm2java
 */
@Entity
@Table(name = "tdoctors")
public class TDoctors implements java.io.Serializable {

	private int doctorId;
	private String doctorName;
	private String doctorSurname;
	private String doctorPatronymic;
	private String licenseNumber;
	private String password;
	private Set<TMedicalRecords> tmedicalRecordses = new HashSet<TMedicalRecords>(0);
	private Set<THospitalDoctors> thospitalDoctorses = new HashSet<THospitalDoctors>(0);

	public TDoctors() {
	}

	public TDoctors( String doctorName, String doctorSurname, String doctorPatronymic,
			String licenseNumber, String password) {
		this.doctorName = doctorName;
		this.doctorSurname = doctorSurname;
		this.doctorPatronymic = doctorPatronymic;
		this.licenseNumber = licenseNumber;
		this.password = password;
	}

	public TDoctors(int doctorId, String doctorName, String doctorSurname, String doctorPatronymic,
			String licenseNumber, String password, Set<TMedicalRecords> tmedicalRecordses,
			Set<THospitalDoctors> thospitalDoctorses) {
		this.doctorId = doctorId;
		this.doctorName = doctorName;
		this.doctorSurname = doctorSurname;
		this.doctorPatronymic = doctorPatronymic;
		this.licenseNumber = licenseNumber;
		this.password = password;
		this.tmedicalRecordses = tmedicalRecordses;
		this.thospitalDoctorses = thospitalDoctorses;
	}

	@Id
	@SequenceGenerator(name="pk_sequence",sequenceName="tdoctors_doctor_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
	@Column(name = "doctor_id", unique = true, nullable = false)
	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	@Column(name = "doctor_name", nullable = false, length = 50)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "doctor_surname", nullable = false, length = 50)
	public String getDoctorSurname() {
		return this.doctorSurname;
	}

	public void setDoctorSurname(String doctorSurname) {
		this.doctorSurname = doctorSurname;
	}

	@Column(name = "doctor_patronymic", length = 50)
	public String getDoctorPatronymic() {
		return this.doctorPatronymic;
	}

	public void setDoctorPatronymic(String doctorPatronymic) {
		this.doctorPatronymic = doctorPatronymic;
	}

	@Column(name = "license_number", length = 20)
	public String getLicenseNumber() {
		return this.licenseNumber;
	}

	public void setLicenseNumber(String licenseNumber) {
		this.licenseNumber = licenseNumber;
	}

	@Column(name = "password", length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tdoctors")
	public Set<TMedicalRecords> getTmedicalRecordses() {
		return this.tmedicalRecordses;
	}

	public void setTmedicalRecordses(Set<TMedicalRecords> tmedicalRecordses) {
		this.tmedicalRecordses = tmedicalRecordses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tdoctors")
	public Set<THospitalDoctors> getThospitalDoctorses() {
		return this.thospitalDoctorses;
	}

	public void setThospitalDoctorses(Set<THospitalDoctors> thospitalDoctorses) {
		this.thospitalDoctorses = thospitalDoctorses;
	}


}
