package com.khomenkocode.graduationproject.entities;
// Generated 26.04.2018 1:06:34 by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tdoctors generated by hbm2java
 */
@Entity
@Table(name = "tdoctors")
public class TDoctors implements java.io.Serializable {

	private int doctorId;
	private THospitalDepartments tHospitalDepartments;
	private String doctorName;
	private String doctorSurname;
	private String doctorPatronymic;
	private Set<TMedicalRecords> tmedicalRecordses = new HashSet<TMedicalRecords>(0);

	public TDoctors() {
	}

	public TDoctors(int doctorId, THospitalDepartments tHospitalDepartments, String doctorName, String doctorSurname) {
		this.doctorId = doctorId;
		this.tHospitalDepartments = tHospitalDepartments;
		this.doctorName = doctorName;
		this.doctorSurname = doctorSurname;
	}

	public TDoctors(int doctorId, THospitalDepartments tHospitalDepartments, String doctorName, String doctorSurname,
			String doctorPatronymic, Set<TMedicalRecords> tmedicalRecordses) {
		this.doctorId = doctorId;
		this.tHospitalDepartments = tHospitalDepartments;
		this.doctorName = doctorName;
		this.doctorSurname = doctorSurname;
		this.doctorPatronymic = doctorPatronymic;
		this.tmedicalRecordses = tmedicalRecordses;
	}

	@Id

	@Column(name = "doctor_id", unique = true, nullable = false)
	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hospital_department_id", nullable = false)
	public THospitalDepartments getThospitalDepartments() {
		return this.tHospitalDepartments;
	}

	public void setThospitalDepartments(THospitalDepartments tHospitalDepartments) {
		this.tHospitalDepartments = tHospitalDepartments;
	}

	@Column(name = "doctor_name", nullable = false, length = 50)
	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	@Column(name = "doctor_surname", nullable = false, length = 50)
	public String getDoctorSurname() {
		return this.doctorSurname;
	}

	public void setDoctorSurname(String doctorSurname) {
		this.doctorSurname = doctorSurname;
	}

	@Column(name = "doctor_patronymic", length = 50)
	public String getDoctorPatronymic() {
		return this.doctorPatronymic;
	}

	public void setDoctorPatronymic(String doctorPatronymic) {
		this.doctorPatronymic = doctorPatronymic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tdoctors")
	public Set<TMedicalRecords> getTmedicalRecordses() {
		return this.tmedicalRecordses;
	}

	public void setTmedicalRecordses(Set<TMedicalRecords> tmedicalRecordses) {
		this.tmedicalRecordses = tmedicalRecordses;
	}

}
