package com.khomenkocode.graduationproject.entities;
// Generated 26.04.2018 1:06:34 by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ThospitalDepartments generated by hbm2java
 */
@Entity
@Table(name = "thospital_departments")
public class THospitalDepartments implements java.io.Serializable {

	private int hospitalDepartmentId;
	private THospitals tHospitals;
	private Long hospitalDepartment;
	private Set<TDoctors> tdoctorses = new HashSet<TDoctors>(0);

	public THospitalDepartments() {
	}

	public THospitalDepartments(int hospitalDepartmentId, THospitals tHospitals) {
		this.hospitalDepartmentId = hospitalDepartmentId;
		this.tHospitals = tHospitals;
	}

	public THospitalDepartments(int hospitalDepartmentId, THospitals tHospitals, Long hospitalDepartment,
			Set<TDoctors> tdoctorses) {
		this.hospitalDepartmentId = hospitalDepartmentId;
		this.tHospitals = tHospitals;
		this.hospitalDepartment = hospitalDepartment;
		this.tdoctorses = tdoctorses;
	}

	@Id

	@Column(name = "hospital_department_id", unique = true, nullable = false)
	public int getHospitalDepartmentId() {
		return this.hospitalDepartmentId;
	}

	public void setHospitalDepartmentId(int hospitalDepartmentId) {
		this.hospitalDepartmentId = hospitalDepartmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hospital_id", nullable = false)
	public THospitals getThospitals() {
		return this.tHospitals;
	}

	public void setThospitals(THospitals tHospitals) {
		this.tHospitals = tHospitals;
	}

	@Column(name = "hospital_department")
	public Long getHospitalDepartment() {
		return this.hospitalDepartment;
	}

	public void setHospitalDepartment(Long hospitalDepartment) {
		this.hospitalDepartment = hospitalDepartment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thospitalDepartments")
	public Set<TDoctors> getTdoctorses() {
		return this.tdoctorses;
	}

	public void setTdoctorses(Set<TDoctors> tdoctorses) {
		this.tdoctorses = tdoctorses;
	}

}
