package com.khomenkocode.graduationproject.entities;
// Generated 07.05.2018 15:13:57 by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Thospitals generated by hbm2java
 */
@Entity
@Table(name = "thospitals")
public class THospitals implements java.io.Serializable {

	private int hospitalId;
	private String hospitalName;
	private String hospitalAdress;
	private Set<THospitalDoctors> thospitalDoctorses = new HashSet<THospitalDoctors>(0);

	public THospitals() {
	}

	public THospitals(String hospitalName, String hospitalAdress) {
		this.hospitalName = hospitalName;
		this.hospitalAdress = hospitalAdress;
	}

	public THospitals(String hospitalName, String hospitalAdress,
			Set<THospitalDoctors> thospitalDoctorses) {
		this.hospitalName = hospitalName;
		this.hospitalAdress = hospitalAdress;
		this.thospitalDoctorses = thospitalDoctorses;
	}

	@Id
	@SequenceGenerator(name="pk_sequence",sequenceName="thospitals_hospital_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
	@Column(name = "hospital_id", unique = true, nullable = false)
	public int getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(int hospitalId) {
		this.hospitalId = hospitalId;
	}

	@Column(name = "hospital_name", length = 100)
	public String getHospitalName() {
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	@Column(name = "hospital_adress", length = 150)
	public String getHospitalAdress() {
		return this.hospitalAdress;
	}

	public void setHospitalAdress(String hospitalAdress) {
		this.hospitalAdress = hospitalAdress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thospitals")
	public Set<THospitalDoctors> getThospitalDoctorses() {
		return this.thospitalDoctorses;
	}

	public void setThospitalDoctorses(Set<THospitalDoctors> thospitalDoctorses) {
		this.thospitalDoctorses = thospitalDoctorses;
	}

}
