package com.khomenkocode.graduationproject.entities;
// Generated 26.04.2018 1:06:34 by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Thospitals generated by hbm2java
 */
@Entity
@Table(name = "thospitals")
public class THospitals implements java.io.Serializable {

	private int hospitalId;
	private String hospitalName;
	private String hospitalAdress;
	private Set<THospitalDepartments> thospitalDepartmentses = new HashSet<THospitalDepartments>(0);

	public THospitals() {
	}

	public THospitals(int hospitalId) {
		this.hospitalId = hospitalId;
	}

	public THospitals(int hospitalId, String hospitalName, String hospitalAdress,
			Set<THospitalDepartments> thospitalDepartmentses) {
		this.hospitalId = hospitalId;
		this.hospitalName = hospitalName;
		this.hospitalAdress = hospitalAdress;
		this.thospitalDepartmentses = thospitalDepartmentses;
	}

	@Id

	@Column(name = "hospital_id", unique = true, nullable = false)
	public int getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(int hospitalId) {
		this.hospitalId = hospitalId;
	}

	@Column(name = "hospital_name", length = 100)
	public String getHospitalName() {
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	@Column(name = "hospital_adress", length = 150)
	public String getHospitalAdress() {
		return this.hospitalAdress;
	}

	public void setHospitalAdress(String hospitalAdress) {
		this.hospitalAdress = hospitalAdress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thospitals")
	public Set<THospitalDepartments> getThospitalDepartmentses() {
		return this.thospitalDepartmentses;
	}

	public void setThospitalDepartmentses(Set<THospitalDepartments> thospitalDepartmentses) {
		this.thospitalDepartmentses = thospitalDepartmentses;
	}

}
