package com.khomenkocode.graduationproject.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Timages generated by hbm2java
 */
@Entity
@Table(name = "timages")
public class TImages implements java.io.Serializable {

	private int imageId;
	private TMedicalRecords tmedicalRecords;
	private String imageName;
	private String imageUrl;

	public TImages() {
	}

	public TImages(TMedicalRecords tmedicalRecords, String imageName, String imageUrl) {
		this.tmedicalRecords = tmedicalRecords;
		this.imageName = imageName;
		this.imageUrl = imageUrl;
	}

	@Id
	@SequenceGenerator(name="pk_sequence",sequenceName="timages_image_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
	@Column(name = "image_id", unique = true, nullable = false)
	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medical_record_id", nullable = false)
	public TMedicalRecords getTmedicalRecords() {
		return this.tmedicalRecords;
	}

	public void setTmedicalRecords(TMedicalRecords tmedicalRecords) {
		this.tmedicalRecords = tmedicalRecords;
	}

	@Column(name = "image_name", nullable = false, length = 200)
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "image_url", nullable = false, length = 200)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

}
