package com.khomenkocode.graduationproject.entities;
// Generated 07.05.2018 15:13:57 by Hibernate Tools 5.1.4.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmedicalRecords generated by hbm2java
 */
@Entity
@Table(name = "tmedical_records")
public class TMedicalRecords implements java.io.Serializable {

	private int medicalRecordId;
	private TDoctors tDoctors;
	private TPatients tPatients;
	private String medicalRecord;
	private Date medicalRecordDate;
	//TODO No lazy load images
	private Set<TImages> timageses = new HashSet<TImages>(0);

	public TMedicalRecords() {
	}

	public TMedicalRecords(TDoctors tDoctors, TPatients tPatients, String medicalRecord,
			Date medicalRecordDate) {
		this.tDoctors = tDoctors;
		this.tPatients = tPatients;
		this.medicalRecord = medicalRecord;
		this.medicalRecordDate = medicalRecordDate;
	}

	public TMedicalRecords(int medicalRecordId, TDoctors tDoctors, TPatients tPatients, String medicalRecord,
			Date medicalRecordDate) {
		this.medicalRecordId = medicalRecordId;
		this.tDoctors = tDoctors;
		this.tPatients = tPatients;
		this.medicalRecord = medicalRecord;
		this.medicalRecordDate = medicalRecordDate;
	}
	
	@Id
	@SequenceGenerator(name="pk_sequence",sequenceName="tmedical_records_medical_record_id_seq", allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
	@Column(name = "medical_record_id", unique = true, nullable = false)
	public int getMedicalRecordId() {
		return this.medicalRecordId;
	}

	public void setMedicalRecordId(int medicalRecordId) {
		this.medicalRecordId = medicalRecordId;
	}

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "doctor_id", nullable = false)
	public TDoctors getTdoctors() {
		return this.tDoctors;
	}

	public void setTdoctors(TDoctors tDoctors) {
		this.tDoctors = tDoctors;
	}

	@ManyToOne( fetch=FetchType.EAGER)
	@JoinColumn(name = "patient_id", nullable = false)
	public TPatients getTpatients() {
		return this.tPatients;
	}

	public void setTpatients(TPatients tPatients) {
		this.tPatients = tPatients;
	}

	@Column(name = "medical_record", nullable = false)
	public String getMedicalRecord() {
		return this.medicalRecord;
	}

	public void setMedicalRecord(String medicalRecord) {
		this.medicalRecord = medicalRecord;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "medical_record_date", nullable = false, length = 29)
	public Date getMedicalRecordDate() {
		return this.medicalRecordDate;
	}

	public void setMedicalRecordDate(Date medicalRecordDate) {
		this.medicalRecordDate = medicalRecordDate;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmedicalRecords")
	public Set<TImages> getTimageses() {
		return this.timageses;
	}

	public void setTimageses(Set<TImages> timageses) {
		this.timageses = timageses;
	}
}
