package com.khomenkocode.graduationproject.entities;
// Generated 07.05.2018 15:13:57 by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tpatients generated by hbm2java
 */
@Entity
@Table(name = "tpatients")
public class TPatients implements java.io.Serializable {

	private String patientId;
	private String patientName;
	private String patientSurname;
	private String patientPatronymic;
	private Set<TMedicalRecords> tmedicalRecordses = new HashSet<TMedicalRecords>(0);

	public TPatients() {
	}

	public TPatients(String patientId, String patientName, String patientSurname) {
		this.patientId = patientId;
		this.patientName = patientName;
		this.patientSurname = patientSurname;
	}

	public TPatients(String patientId, String patientName, String patientSurname, String patientPatronymic,
			Set<TMedicalRecords> tmedicalRecordses) {
		this.patientId = patientId;
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.patientPatronymic = patientPatronymic;
		this.tmedicalRecordses = tmedicalRecordses;
	}

	@Id

	@Column(name = "patient_id", unique = true, nullable = false, length = 128)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "patient_name", nullable = false, length = 50)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "patient_surname", nullable = false, length = 50)
	public String getPatientSurname() {
		return this.patientSurname;
	}

	public void setPatientSurname(String patientSurname) {
		this.patientSurname = patientSurname;
	}

	@Column(name = "patient_patronymic", length = 50)
	public String getPatientPatronymic() {
		return this.patientPatronymic;
	}

	public void setPatientPatronymic(String patientPatronymic) {
		this.patientPatronymic = patientPatronymic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpatients")
	public Set<TMedicalRecords> getTmedicalRecordses() {
		return this.tmedicalRecordses;
	}

	public void setTmedicalRecordses(Set<TMedicalRecords> tmedicalRecordses) {
		this.tmedicalRecordses = tmedicalRecordses;
	}


}
