package com.khomenkocode.graduationproject.entities;
// Generated 07.05.2018 15:13:57 by Hibernate Tools 5.1.4.Final

import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Tpatients generated by hbm2java
 */
@Entity
@Table(name = "tpatients")
public class TPatients implements java.io.Serializable {

	private String patientId;
	private String patientName;
	private String patientSurname;
	private String patientPatronymic;
	private Set<TMedicalRecords> tmedicalRecordses = new HashSet<TMedicalRecords>(0);
	private String email;
	private String password;
	private String patientBloodGroup;
	private String patientRhFactor;
	private String patientAllergiesInfo;
	
	public TPatients() {
	}

	public TPatients(String patientName, String patientSurname, String EMail, String password) {
		this.patientId = generateId();
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.email = EMail;
		this.password = password;
	}
	
	public TPatients(String patientName, String patientSurname, String patientPatronymic, String EMail, String password) {
		this.patientId = generateId();
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.email = EMail;
		this.password = password;
	}
	
	public TPatients(String patientName, String patientSurname, String patientPatronymic,
			String EMail, String password, String patientBloodGroup, String patientRhFactor,
			String patientAllergiesInfo) {
		this.patientId = generateId();
		this.patientName = patientName;
		this.patientSurname = patientSurname;
		this.patientPatronymic = patientPatronymic;
		this.email = EMail;
		this.password = password;
		this.patientBloodGroup = patientBloodGroup;
		this.patientRhFactor = patientRhFactor;
		this.patientAllergiesInfo = patientAllergiesInfo;
	}

	private String generateId(){
		String abc = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM1234567890";
		int length = abc.length();
		String id = "";
		Random rand = new Random();
		for(int i=0; i<128; i++)
			id += abc.charAt(Math.abs(rand.nextInt())%length);
		
		return id;
	} 
	
	@Id

	@Column(name = "patient_id", unique = true, nullable = false, length = 128)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "patient_name", nullable = false, length = 50)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "patient_surname", nullable = false, length = 50)
	public String getPatientSurname() {
		return this.patientSurname;
	}

	public void setPatientSurname(String patientSurname) {
		this.patientSurname = patientSurname;
	}

	@Column(name = "patient_patronymic", length = 50)
	public String getPatientPatronymic() {
		return this.patientPatronymic;
	}

	public void setPatientPatronymic(String patientPatronymic) {
		this.patientPatronymic = patientPatronymic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpatients")
	public Set<TMedicalRecords> getTmedicalRecordses() {
		return this.tmedicalRecordses;
	}

	public void setTmedicalRecordses(Set<TMedicalRecords> tmedicalRecordses) {
		this.tmedicalRecordses = tmedicalRecordses;
	}


	@Column(name = "e_mail", length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "patient_blood_group", length = 5)
	public String getPatientBloodGroup() {
		return this.patientBloodGroup;
	}

	public void setPatientBloodGroup(String patientBloodGroup) {
		this.patientBloodGroup = patientBloodGroup;
	}

	@Column(name = "patient_rh_factor", length = 20)
	public String getPatientRhFactor() {
		return this.patientRhFactor;
	}

	public void setPatientRhFactor(String patientRhFactor) {
		this.patientRhFactor = patientRhFactor;
	}

	@Column(name = "patient_allergies_info")
	public String getPatientAllergiesInfo() {
		return this.patientAllergiesInfo;
	}

	public void setPatientAllergiesInfo(String patientAllergiesInfo) {
		this.patientAllergiesInfo = patientAllergiesInfo;
	}
}
